name: Generate Random Words

on:
  workflow_dispatch:

jobs:
  generate-words:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Use the latest version

    - name: Install Node.js
      uses: actions/setup-node@v3  # Use the latest version
      with:
        node-version: '20'  # Use Node.js 20

    - name: Generate Random Words
      run: |
        echo "Initializing npm project..."
        npm init -y
        echo "Installing random-words package..."
        npm install random-words
        echo "Generating random words..."
        node -e "
          const randomWords = require('random-words');
          const adjectives = randomWords({ exactly: 1, wordsPerString: 1, formatter: (word, index) => {
            return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
          }});
          const nouns = randomWords({ exactly: 1, wordsPerString: 1, formatter: (word, index) => {
            return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
          }});
          const text = adjectives[0] + ' ' + nouns[0];
          const fs = require('fs');
          fs.writeFileSync('random_words.txt', text);
          console.log('Generated words:', text);
        "

    - name: Commit Random Words
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add random_words.txt
        git commit -m "Generated random words"
        git push origin main
